name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.20'

      - name: Build Drone Server Linux amd64
        run: |
          git clone https://github.com/drone/drone.git
          cd drone && \
          go build -o ../release/linux/amd64/drone-server -ldflags "-extldflags \"-static\"" -tags "nolimit" github.com/drone/drone/cmd/drone-server

      - name: Upload Bin
        uses: actions/upload-artifact@v3
        with:
          name: drone-server
          path: drone/

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ibook163/drone
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile.server.linux.amd64
