name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.17'

      - name: Build Drone Server Linux amd64
        run: |
          git clone https://github.com/drone/drone.git
          cd drone && \
          go build -ldflags "-extldflags \"-static\"" -tags "nolimit" github.com/drone/drone/cmd/drone-server

      - name: Upload Bin
        uses: actions/upload-artifact@v2
        with:
          name: drone-server
          path: drone/

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ibook163/drone
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile.server.linux.amd64
